import React, { useState } from 'react';
import { approveCoachApplication } from '../../services/firestoreService';
import Button from '../ui/Button';
import Input from '../ui/Input';
import { useAuth } from '../../context/AuthContext';
import { useTheme } from '../../context/ThemeContext';
import './DemoOutcomeModal.css';

import { createCoachAccount } from '../../services/adminAuthService';

const EMAIL_API_URL = import.meta.env.VITE_EMAIL_API_URL || 'http://localhost:3001';

const ApproveCoachModal = ({ application, onClose, onSuccess }) => {
    const { currentUser } = useAuth();
    const { isDark } = useTheme();

    // Auto-generate coach email from coach name
    const coachEmailPrefix = application.fullName.toLowerCase().split(' ')[0].replace(/[^a-z0-9]/g, '');
    const autoGeneratedEmail = `${coachEmailPrefix}@coach.com`;

    const [coachEmail, setCoachEmail] = useState(autoGeneratedEmail); // Auto-generated, but editable
    const [password, setPassword] = useState('');
    const [assignedGroup, setAssignedGroup] = useState('');
    const [batchOption, setBatchOption] = useState('Batch 1');
    const [customBatch, setCustomBatch] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');

    const GROUP_OPTIONS = ['Beginner', 'Advanced Beginner', 'Intermediate-I', 'Intermediate-II'];
    const BATCH_PRESETS = ['Batch 1', 'Batch 2', 'Batch 3', 'Batch 4', 'Custom'];
    const assignedBatch = batchOption === 'Custom' ? customBatch : batchOption;

    if (!application) return null;

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        // Validate email not empty or whitespace
        if (!coachEmail.trim()) {
            setError('Coach email is required');
            setLoading(false);
            return;
        }

        // Validate email format - MUST be @coach.com
        const trimmedEmail = coachEmail.trim();
        if (!trimmedEmail.endsWith('@coach.com')) {
            setError('Coach email MUST end with @coach.com (e.g., john@coach.com)');
            setLoading(false);
            return;
        }

        // Validate email format is not just @coach.com
        const emailPart = trimmedEmail.replace('@coach.com', '');
        if (!emailPart || emailPart.length < 3) {
            setError('Coach email must have a valid name part (e.g., john.doe@coach.com)');
            setLoading(false);
            return;
        }

        if (!password.trim()) {
            setError('Please set a temporary password');
            setLoading(false);
            return;
        }

        if (!assignedGroup) {
            setError('Please assign a group to this coach');
            setLoading(false);
            return;
        }

        if (!assignedBatch.trim()) {
            setError('Please enter or select a batch');
            setLoading(false);
            return;
        }

        try {
            // 1. Create Firebase Auth Account (Secondary App)
            const authResult = await createCoachAccount(trimmedEmail, password);

            if (!authResult.success) {
                // If account already exists (e.g. reused email), we might proceed or error.
                // For now, let's treat it as an error but maybe allow proceed if it's "email-already-in-use"
                if (authResult.error.includes('email-already-in-use')) {
                    // Optional: Allow approval linking to existing account?
                    // For now, throw error to be safe
                    throw new Error('An account with this email already exists. Cannot create new credentials.');
                }
                throw new Error(authResult.error);
            }

            const newUid = authResult.uid;

            // 2. Approve in Firestore (Create Profile/Account Docs)
            const result = await approveCoachApplication(application.id, newUid, password, currentUser?.uid, trimmedEmail, application.fullName, assignedGroup, assignedBatch);

            if (result.success) {
                // Send welcome email with credentials via nodemailer
                try {
                    const emailResponse = await fetch(`${EMAIL_API_URL}/api/email/send`, {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({
                            to: trimmedEmail,
                            subject: 'Welcome to Indian Chess Academy - Coach Account Approved! 🎉',
                            text: `Dear ${application.fullName},

Congratulations! Your application as a coach at Indian Chess Academy has been APPROVED! 🎉

🔑 Your Login Credentials:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Email: ${coachEmail}
• Temporary Password: ${password}
• Login URL: ${window.location.origin}/login

📋 Next Steps:
1. Login using the credentials above
2. Change your password in Settings (important!)
3. Complete your coach profile
4. Wait for batch assignments from the admin team

We're excited to have you on our team and look forward to working together to shape the next generation of chess champions!

Best regards,
Indian Chess Academy Team

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📧 Support: indianchessacademy@chess.com
🌐 Website: www.indianchessacademy.com`
                        })
                    });

                    if (emailResponse.ok) {
                        console.log('✅ Coach credentials email sent to:', coachEmail);
                    } else {
                        console.error('⚠️ Email send failed, but coach was approved');
                    }
                } catch (emailError) {
                    console.error('Email sending error:', emailError);
                    // Don't fail the approval if email fails
                }

                onSuccess();
            } else {
                setError(result.error);
            }
        } catch (err) {
            console.error(err);
            setError('Approval failed: ' + err.message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="modal-overlay">
            <div className={`modal-content demo-outcome-modal ${isDark ? 'dark-mode' : ''}`}>
                <button className="modal-close" onClick={onClose}>&times;</button>
                <h2>Approve Coach Application</h2>
                <div className="demo-info">
                    <p><strong>Name:</strong> {application.fullName}</p>
                    <p><strong>Email:</strong> {application.email}</p>
                    <p><strong>Experience:</strong> {application.experience} years</p>
                </div>

                {error && <div className="error-message">{error}</div>}

                <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', flex: 1 }}>
                    <div style={{ flex: 1, overflowY: 'auto', paddingRight: '8px', marginBottom: '12px' }}>
                        <div className="form-group">
                            <label>Confirm/Edit Coach Email *</label>
                            <Input
                                name="coachEmail"
                                type="email"
                                required
                                value={coachEmail}
                                onChange={(e) => setCoachEmail(e.target.value)}
                            />
                        </div>

                        <div className="form-group">
                            <label>Set Temporary Password *</label>
                            <p className="description-text" style={{ fontSize: '12px', color: '#666', marginBottom: '8px' }}>
                                Share this password with the coach securely. They will use their email and this password to login.
                            </p>
                            <Input
                                name="password"
                                type="text"
                                required
                                placeholder="e.g. CoachPass@2024"
                                value={password}
                                onChange={(e) => setPassword(e.target.value)}
                            />
                        </div>

                        <div className="form-group">
                            <label>Assign Group *</label>
                            <p className="description-text" style={{ fontSize: '12px', color: '#666', marginBottom: '8px' }}>
                                Select the skill group this coach will teach.
                            </p>
                            <select
                                required
                                value={assignedGroup}
                                onChange={(e) => setAssignedGroup(e.target.value)}
                                style={{ width: '100%', padding: '10px 12px', borderRadius: '8px', border: isDark ? '1px solid rgba(255,255,255,0.15)' : '1px solid #cbd5e1', background: isDark ? '#0f1117' : 'white', color: isDark ? '#f0f0f0' : '#1e293b', fontSize: '14px' }}
                            >
                                <option value="">Select a group...</option>
                                {GROUP_OPTIONS.map(g => (
                                    <option key={g} value={g}>{g}</option>
                                ))}
                            </select>
                        </div>

                        <div className="form-group">
                            <label>Assign Batch *</label>
                            <p className="description-text" style={{ fontSize: '12px', color: '#666', marginBottom: '8px' }}>
                                Choose an existing batch or enter a custom one (e.g. "Batch 5" or "Morning Batch").
                            </p>
                            <select
                                value={batchOption}
                                onChange={(e) => { setBatchOption(e.target.value); setCustomBatch(''); }}
                                style={{ width: '100%', padding: '10px 12px', borderRadius: '8px', border: isDark ? '1px solid rgba(255,255,255,0.15)' : '1px solid #cbd5e1', background: isDark ? '#0f1117' : 'white', color: isDark ? '#f0f0f0' : '#1e293b', fontSize: '14px', marginBottom: batchOption === 'Custom' ? '8px' : '0' }}
                            >
                                {BATCH_PRESETS.map(b => (
                                    <option key={b} value={b}>{b}</option>
                                ))}
                            </select>
                            {batchOption === 'Custom' && (
                                <input
                                    type="text"
                                    placeholder="e.g. Batch 5, Morning Batch..."
                                    value={customBatch}
                                    onChange={(e) => setCustomBatch(e.target.value)}
                                    required
                                    style={{ width: '100%', padding: '10px 12px', borderRadius: '8px', border: isDark ? '1px solid rgba(255,255,255,0.15)' : '1px solid #cbd5e1', background: isDark ? '#0f1117' : 'white', color: isDark ? '#f0f0f0' : '#1e293b', fontSize: '14px', boxSizing: 'border-box', marginTop: '4px' }}
                                />
                            )}
                            {assignedGroup && assignedBatch && (
                                <p style={{ fontSize: '12px', color: '#10B981', marginTop: '6px', fontWeight: '500' }}>
                                    ✓ Coach will be assigned: {assignedGroup} — {assignedBatch}
                                </p>
                            )}
                        </div>
                    </div>

                    <div className="modal-actions" style={{ marginTop: 'auto' }}>
                        <Button type="button" variant="secondary" onClick={onClose}>Cancel</Button>
                        <Button type="submit" disabled={loading}>
                            {loading ? 'Approving...' : 'Approve & Create Account'}
                        </Button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default ApproveCoachModal;
